ignoredBuiltDependencies:
  - cpu-features
  - eslint-plugin-n8n-nodes-base
  - sharp
  - ssh2

overrides:
  n8n-nodes-zalo: link:../../../../../root/.local/share/pnpm/global/5/node_modules/n8n-nodes-zalo
